### ISSUE TITLE
Replace pycrypto with pycryptodome

### ISSUE THREAD

**Issue by matbech** [abertschi/postcards#15]
I'm having a hard time to install postcards with python 3.6 on Windows. One problem is that pycrypto is required which must be compiled from source. This requires a manual build step (https://stackoverflow.com/questions/41843266/microsoft-windows-python-3-6-pycrypto-installation-error).

I believe if the unmaintained pycrypto is replaced with pycryptodome (https://github.com/Legrandin/pycryptodome) the problem could be overcome, because pycryptodome supports wheel (binary distribution).

Thanks.

**Comment by abertschi** [comment]
A replacement of pycrypto with pycryptodome sounds good to me.

**Comment by abertschi** [comment]
In case you are interested in contribution, you are welcome to submit a PR for this.

**Comment by matbech** [comment]
I'm not really familiar with python. Maybe replacing it in requirements.txt is enough?

**Comment by abertschi** [comment]
#20 removes pycrypto. Try installing the lastest version 0.0.7

**Comment by matbech** [comment]
Works as expected. Thanks.
