### ISSUE TITLE
How to pass new lines to message argument

### ISSUE THREAD

**Issue by matbech** [abertschi/postcards#16]
I was wondering how to pass a new line character to the --message argument. Are escaped strings like \n unescaped by the tool? If not, could this be added?
The reason is that passing a new line inside command line arguments is in particular cumbersome (or some claim impossible) on Windows:
https://superuser.com/questions/1243809/can-i-pass-a-newline-in-a-command-line-parameter-to-a-windows-executable-in-a-ba

**Comment by abertschi** [comment]
`--message` accepts valid html code. A `<br/>` will do the job.

**Comment by matbech** [comment]
Thank you. Maybe this could be documented somewhere? Readme.md?
