### ISSUE TITLE
Files with capitalized file extensions not recognized as images

### ISSUE THREAD

**Issue by pietdevaere** [abertschi/postcards#43]
E.g., `.JPG` is not recognized as an image extension., probably needs a single `.lower()` somewhere.

**Comment by abertschi** [comment]
Feel free to file a PR.

**Comment by pietdevaere** [comment]
Yes, I was planning to do so. However, I am quite busy for the next couple of days, so I thought I would document the issue first.

**Comment by abertschi** [comment]
:+1:

**Comment by elijose55** [comment]
Can I work on this issue or @pietdevaere is working already?

**Comment by abertschi** [comment]
I doubt he has already started. So please, go for it :) :rocket:

**Comment by pietdevaere** [comment]
Can confirm, did not start yet.

**Comment by abertschi** [comment]
#44
