### ISSUE TITLE
Error when parsing Post login website

### ISSUE THREAD

**Issue by mar0th** [abertschi/postcards#45]
When I am trying to send a postcard, I am getting the following error message:

>postcards (DEBUG): using no key
postcards (INFO): checking for valid accounts
postcard_creator (DEBUG): fetching postcard account token
root (INFO): using legacy username password authentication
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://account.post.ch/SAML/IdentityProvider/?login&app=pcc&service=pcc&targetURL=https%3A%2F%2Fpostcardcreator.post.ch&abortURL=https%3A%2F%2Fpostcardcreator.post.ch&inMobileApp=true

**Comment by abertschi** [comment]
There have been some issues with the endpoint last night. They seem to be resolved however.
If the issue still persists you have to give more context how to reproduce the problem.
