### ISSUE TITLE
Rendering line breaks in `message`

### ISSUE THREAD

**Issue by jorisnoo** [abertschi/postcards#55]
Thanks again for your continued work on this library, @abertschi!
Following the example,  I sent a card with `--message "Happy <br/> coding!"`. However, the `<br/>` tag always gets rendered as text instead of being converted to a line break.

(With my limited python experience) I tried adding something like
```
msg = msg.replace("<br />", "\n").replace("<br/>", "\n").replace("<br>", "\n")
```
before passing the text to `create_text_image`, which seems to solve this.

**Comment by abertschi** [comment]
As far as I recall, html tags are no longer supported with the update to a text cover which is pixel and no longer text based. I should update the readme and remove these examples. Feel free to create a pull request which uses newlines i.e. `\n` in the examples instead.

**Comment by jorisnoo** [comment]
Thank you — you're right!
